package life.pips.strat1

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import life.pips.strat1.data.*
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

private val Bg = Color(0xFF050A12); private val Panel = Color(0xFF0C1422); private val TextMain = Color(0xFFF4F7FB); private val Muted = Color(0xFF8EA2BB); private val Cyan = Color(0xFF27D8FF); private val Green = Color(0xFF43F28E); private val Red = Color(0xFFFF5872); private val Purple = Color(0xFFB36BFF)

class MainActivity : ComponentActivity() { override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); setContent { PipsLifeApp() } } }
private enum class Tab { HOME, METAAPI, STRATEGY, WATCHLIST, ACTIVITY }

@Composable private fun PipsLifeApp() {
    val context = androidx.compose.ui.platform.LocalContext.current; val scope = rememberCoroutineScope(); val meta = remember { DirectMetaApiClient() }; val flash = remember { FlashAlphaClient() }; val strategy = remember { Strategy001Engine() }
    var tab by remember { mutableStateOf(Tab.HOME) }; var saved by remember { mutableStateOf(SavedConnection("", "", "", "", "", "")) }; var account by remember { mutableStateOf<MetaAccount?>(null) }; var snapshot by remember { mutableStateOf<MetaSnapshot?>(null) }; var flashData by remember { mutableStateOf<FlashAlphaSnapshot?>(null) }; var running by remember { mutableStateOf(false) }; var armed by remember { mutableStateOf(false) }; var busy by remember { mutableStateOf(false) }; var status by remember { mutableStateOf("Ready — direct connections only") }; var selectedSymbol by remember { mutableStateOf("XAUUSD") }; var flashSymbol by remember { mutableStateOf("SPY") }
    LaunchedEffect(Unit) { saved = context.loadSavedConnection(); selectedSymbol = saved.watchlist.split(',').firstOrNull()?.trim().orEmpty().ifBlank { "XAUUSD" }; if (saved.accountId.isNotBlank() && saved.metaApiToken.isNotBlank()) account = meta.connectExisting(saved.metaApiToken, saved.accountId).getOrNull() }
    LaunchedEffect(account, running, armed, selectedSymbol, flashSymbol) {
        val a = account ?: return@LaunchedEffect
        while (true) {
            if (saved.metaApiToken.isBlank()) { delay(1000); continue }
            meta.refresh(saved.metaApiToken, a, saved.watchlist.split(',')).onSuccess { s -> snapshot = s; status = "MetaApi ${s.account.connectionStatus}" }.onFailure { status = it.message ?: "MetaApi refresh failed" }
            if (saved.flashAlphaKey.isNotBlank()) flash.snapshot(saved.flashAlphaKey, flashSymbol).onSuccess { flashData = it }.onFailure { if (running) status = it.message ?: "FlashAlpha failed" }
            if (running && armed && saved.flashAlphaKey.isNotBlank()) executeStrategy001(meta, strategy, a, saved, selectedSymbol, snapshot, flashData) { status = it }
            delay(5000)
        }
    }
    MaterialTheme(colorScheme = darkColorScheme(background = Bg, surface = Panel, primary = Cyan, secondary = Green, error = Red)) {
        Scaffold(containerColor = Bg, bottomBar = { NavigationBar(containerColor = Color(0xFF08111D)) { listOf(Tab.HOME to "HOME", Tab.METAAPI to "METAAPI", Tab.STRATEGY to "STRATEGY", Tab.WATCHLIST to "WATCH", Tab.ACTIVITY to "ACTIVITY").forEach { (t, label) -> NavigationBarItem(selected = tab == t, onClick = { tab = t }, icon = {}, label = { Text(label, fontSize = 8.sp) }) } } }) { pad ->
            when (tab) {
                Tab.HOME -> Home(Modifier.padding(pad), account, snapshot, flashData, running, armed) { tab = Tab.METAAPI }
                Tab.METAAPI -> MetaApiTab(Modifier.padding(pad), saved, account, busy, status, onSave = { saved = it; scope.launch { context.saveConnection(it) } }, onConnect = { c -> busy = true; scope.launch { val r = if (c.accountId.isNotBlank()) meta.connectExisting(c.metaApiToken, c.accountId) else meta.createAndDeploy(c.metaApiToken, c.login, c.password, c.server); r.onSuccess { x -> account = x; saved = c.copy(accountId = x.id); context.saveConnection(saved); status = "CONNECTED — ${x.login} / ${x.server}" }.onFailure { status = it.message ?: "Connection failed" }; busy = false } })
                Tab.STRATEGY -> StrategyTab(Modifier.padding(pad), saved, flashData, snapshot, selectedSymbol, flashSymbol, running, armed, onFlashSymbol = { flashSymbol = it }, onState = { r, a -> running = r; armed = a; if (!r) armed = false }, onSaveKey = { key -> saved = saved.copy(flashAlphaKey = key); scope.launch { context.saveConnection(saved) } }, engine = strategy)
                Tab.WATCHLIST -> WatchlistTab(Modifier.padding(pad), saved, snapshot, selectedSymbol) { value -> selectedSymbol = value.split(',').firstOrNull()?.trim().orEmpty().ifBlank { selectedSymbol }; saved = saved.copy(watchlist = value); scope.launch { context.saveConnection(saved) } }
                Tab.ACTIVITY -> ActivityTab(Modifier.padding(pad), status, account, running, armed, flashData)
            }
        }
    }
}

private suspend fun executeStrategy001(meta: DirectMetaApiClient, engine: Strategy001Engine, account: MetaAccount, saved: SavedConnection, symbol: String, snapshot: MetaSnapshot?, flash: FlashAlphaSnapshot?, setStatus: (String) -> Unit) {
    val s = snapshot ?: return; val f = flash ?: return; val tick = s.prices[symbol] ?: return; val price = (tick.bid + tick.ask) / 2.0; val plan = engine.evaluate(f, price); val positions = s.positions.filter { it.symbol.equals(symbol, true) }
    for (p in positions) { val exit = engine.exitDecision(plan, p, price); if (exit.close) meta.closePosition(saved.metaApiToken, account, p.id).onSuccess { setStatus("Strategy 001 exit confirmed: ${p.id} — ${exit.reason}") }.onFailure { setStatus(it.message ?: "Strategy 001 exit failed") } }
    if (positions.isNotEmpty() || positions.size >= 4 || plan.side == null || !engine.entryAllowed(plan, price)) return
    val target = plan.exitZone?.center ?: return; val stop = plan.invalidation ?: return; val entryPrice = if (plan.side == TradeSide.BUY) tick.ask else tick.bid
    if (plan.side == TradeSide.BUY && target <= entryPrice) return; if (plan.side == TradeSide.SELL && target >= entryPrice) return
    meta.marketOrder(saved.metaApiToken, account, plan.side, symbol, 0.01, stopLoss = stop, takeProfit = target).onSuccess { setStatus("Strategy 001 ${plan.side} confirmed: ${it.stringCode} ${it.orderId} — ${plan.reason}") }.onFailure { setStatus(it.message ?: "Strategy 001 entry failed") }
}

@Composable private fun Header(title: String, subtitle: String) { Column(Modifier.fillMaxWidth().padding(top = 18.dp, bottom = 8.dp)) { Text("Pips-life", color = Cyan, fontSize = 25.sp, fontWeight = FontWeight.Black); Text(title, color = TextMain, fontSize = 21.sp, fontWeight = FontWeight.Bold); Text(subtitle, color = Muted, fontSize = 11.sp) } }
@Composable private fun Home(modifier: Modifier, account: MetaAccount?, snapshot: MetaSnapshot?, flash: FlashAlphaSnapshot?, running: Boolean, armed: Boolean, connect: () -> Unit) { LazyColumn(modifier.fillMaxSize().padding(horizontal = 16.dp), verticalArrangement = Arrangement.spacedBy(12.dp), contentPadding = PaddingValues(bottom = 24.dp)) { item { Header("Command Center", "Android → MetaApi / FlashAlpha • no backend") }; item { CardBlock { Text("CONNECTION", color = Muted, fontSize = 10.sp); Text(if (account == null) "NOT CONNECTED" else "METAAPI • ${account.connectionStatus}", color = if (account == null) Red else Green, fontWeight = FontWeight.Bold); if (account == null) Button(onClick = connect, modifier = Modifier.fillMaxWidth()) { Text("OPEN METAAPI CONNECTION") } } }; item { CardBlock { Text("STRATEGY 001", color = Muted, fontSize = 10.sp); Text(if (!running) "STOPPED" else if (armed) "LIVE TRADING ARMED" else "MONITORING", color = if (armed) Red else Cyan, fontSize = 19.sp, fontWeight = FontWeight.Black); Text("Data-derived GEX entry zones → opposing GEX exit zones. No 1m candle reversal logic.", color = Muted, fontSize = 11.sp) } }; item { CardBlock { Text("EQUITY", color = Muted, fontSize = 10.sp); Text(money(snapshot?.equity), color = TextMain, fontSize = 29.sp, fontWeight = FontWeight.Black); Text("Balance ${money(snapshot?.balance)} • Free margin ${money(snapshot?.freeMargin)}", color = Muted, fontSize = 11.sp) } }; item { CardBlock { Text("FLASHALPHA GEX", color = Muted, fontSize = 10.sp); Text(flash?.let { "${it.symbol} • ${it.regime}" } ?: "NOT CONNECTED", color = if (flash == null) Muted else Purple, fontWeight = FontWeight.Bold); Text(flash?.let { "Flip ${number(it.gammaFlip)} • Put ${number(it.putWall)} • Call ${number(it.callWall)}" } ?: "Add API key in Strategy", color = Muted, fontSize = 11.sp) } }; item { Text("OPEN POSITIONS", color = Muted, fontSize = 10.sp) }; if (snapshot?.positions?.isNotEmpty() == true) items(snapshot.positions) { CardBlock { Text("${it.symbol} • ${it.type}", color = TextMain, fontWeight = FontWeight.Bold); Text("${it.volume} @ ${number(it.openPrice)} • P/L ${number(it.profit)} • SL ${number(it.stopLoss)} • TP ${number(it.takeProfit)}", color = Muted, fontSize = 11.sp) } } else item { CardBlock { Text("No open positions", color = Muted) } } } }

@Composable private fun MetaApiTab(modifier: Modifier, saved: SavedConnection, account: MetaAccount?, busy: Boolean, status: String, onSave: (SavedConnection) -> Unit, onConnect: (SavedConnection) -> Unit) { var token by remember(saved.metaApiToken) { mutableStateOf(saved.metaApiToken) }; var accountId by remember(saved.accountId) { mutableStateOf(saved.accountId) }; var login by remember(saved.login) { mutableStateOf(saved.login) }; var password by remember(saved.password) { mutableStateOf(saved.password) }; var server by remember(saved.server) { mutableStateOf(saved.server) }; LazyColumn(modifier.fillMaxSize().padding(horizontal = 16.dp), verticalArrangement = Arrangement.spacedBy(10.dp), contentPadding = PaddingValues(bottom = 24.dp)) { item { Header("MetaApi Connection", "Direct account provisioning + direct trade API") }; item { Field("MetaApi auth token", token, { token = it }, true) }; item { Field("Existing MetaApi account ID (optional)", accountId, { accountId = it }) }; item { Field("MT5 login", login, { login = it }) }; item { Field("MT5 password", password, { password = it }, true) }; item { Field("MT5 server", server, { server = it }) }; item { Text("Credentials are encrypted locally with Android Keystore. There is no Pips-life backend.", color = Muted, fontSize = 10.sp) }; item { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) { Button(onClick = { onSave(SavedConnection(token, accountId, login, password, server, saved.flashAlphaKey, saved.watchlist)) }, modifier = Modifier.weight(1f)) { Text("SAVE") }; Button(enabled = !busy && token.isNotBlank(), onClick = { onConnect(SavedConnection(token, accountId, login, password, server, saved.flashAlphaKey, saved.watchlist)) }, modifier = Modifier.weight(1f)) { Text(if (busy) "CONNECTING…" else "CONNECT") } } }; item { CardBlock { Text(status, color = if (account != null) Green else Muted); account?.let { Text("${it.login} • ${it.server} • ${it.region}", color = TextMain, fontWeight = FontWeight.Bold) } } } } }

@Composable private fun StrategyTab(modifier: Modifier, saved: SavedConnection, flash: FlashAlphaSnapshot?, snapshot: MetaSnapshot?, tradeSymbol: String, flashSymbol: String, running: Boolean, armed: Boolean, onFlashSymbol: (String) -> Unit, onState: (Boolean, Boolean) -> Unit, onSaveKey: (String) -> Unit, engine: Strategy001Engine) { var key by remember(saved.flashAlphaKey) { mutableStateOf(saved.flashAlphaKey) }; var symbol by remember(flashSymbol) { mutableStateOf(flashSymbol) }; val price = snapshot?.prices?.get(tradeSymbol)?.let { (it.bid + it.ask) / 2.0 }; val plan = if (flash != null && price != null) engine.evaluate(flash, price) else null; LazyColumn(modifier.fillMaxSize().padding(horizontal = 16.dp), verticalArrangement = Arrangement.spacedBy(10.dp), contentPadding = PaddingValues(bottom = 24.dp)) { item { Header("Strategy 001", "Independent QOF/GEX strategy — its own entry and exit map") }; item { Field("FlashAlpha API key", key, { key = it }, true) }; item { Field("FlashAlpha symbol", symbol, { symbol = it; onFlashSymbol(it) }) }; item { Text("MetaApi trading symbol: $tradeSymbol", color = Muted, fontSize = 11.sp) }; item { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) { Button(onClick = { onSaveKey(key) }, modifier = Modifier.weight(1f)) { Text("SAVE KEY") }; Button(onClick = { onState(!running, false) }, modifier = Modifier.weight(1f)) { Text(if (running) "STOP" else "START") } } }; if (running) item { Button(onClick = { onState(true, !armed) }, modifier = Modifier.fillMaxWidth(), colors = ButtonDefaults.buttonColors(containerColor = if (armed) Red else Green)) { Text(if (armed) "DISARM LIVE TRADING" else "ARM LIVE TRADING") } }; item { CardBlock { Text("GEX MARKET MAP", color = Muted, fontSize = 10.sp); if (plan == null) Text("Waiting for live GEX + MetaApi price", color = Muted) else { Text("${plan.side?.name ?: "WAIT"} • confidence ${plan.confidence}%", color = if (plan.side == null) Muted else Green, fontSize = 20.sp, fontWeight = FontWeight.Black); Text(plan.reason, color = Muted, fontSize = 11.sp); plan.entryZone?.let { Text("ENTRY ${it.kind}: ${number(it.lower)} — ${number(it.upper)} (${it.source})", color = Cyan, fontSize = 11.sp) }; plan.exitZone?.let { Text("EXIT ${it.kind}: ${number(it.lower)} — ${number(it.upper)} (${it.source})", color = Purple, fontSize = 11.sp) }; plan.invalidation?.let { Text("INVALIDATION: ${number(it)}", color = Red, fontSize = 11.sp) } } } }; item { CardBlock { Text("IMPORTANT", color = Muted, fontSize = 10.sp); Text("Strategy 001 does not use 1-minute candle reversal for entry or exit. GEX/flow data defines its market map, entry zone, invalidation and opposing exit zone. Other strategies have their own engines and cannot change this strategy's rules.", color = TextMain, fontSize = 11.sp) } } } }

@Composable private fun WatchlistTab(modifier: Modifier, saved: SavedConnection, snapshot: MetaSnapshot?, selected: String, onSave: (String) -> Unit) { var text by remember(saved.watchlist) { mutableStateOf(saved.watchlist) }; LazyColumn(modifier.fillMaxSize().padding(horizontal = 16.dp), verticalArrangement = Arrangement.spacedBy(10.dp), contentPadding = PaddingValues(bottom = 24.dp)) { item { Header("Market Watchlist", "Actual MetaApi symbols — stored locally") }; item { Field("Comma-separated MetaApi symbols", text, { text = it }) }; item { Button(onClick = { onSave(text) }, modifier = Modifier.fillMaxWidth()) { Text("SAVE WATCHLIST") } }; item { Text("Selected: $selected", color = Cyan, fontWeight = FontWeight.Bold) }; snapshot?.prices?.forEach { (symbol, tick) -> item { CardBlock { Text(symbol, color = TextMain, fontWeight = FontWeight.Bold); Text("Bid ${number(tick.bid)} • Ask ${number(tick.ask)}", color = Muted, fontSize = 11.sp) } } } } }

@Composable private fun ActivityTab(modifier: Modifier, status: String, account: MetaAccount?, running: Boolean, armed: Boolean, flash: FlashAlphaSnapshot?) { LazyColumn(modifier.fillMaxSize().padding(horizontal = 16.dp), verticalArrangement = Arrangement.spacedBy(10.dp), contentPadding = PaddingValues(bottom = 24.dp)) { item { Header("Activity", "Runtime state and strategy isolation") }; item { CardBlock { Text(status, color = TextMain); Text("MetaApi: ${account?.connectionStatus ?: "not connected"}", color = Muted); Text("Strategy 001: ${if (running) if (armed) "armed" else "monitoring" else "stopped"}", color = Muted); Text("FlashAlpha: ${flash?.symbol ?: "not connected"}", color = Muted); Text("No Vercel • No Render • No backend", color = Green, fontWeight = FontWeight.Bold) } } } }

@Composable private fun CardBlock(content: @Composable ColumnScope.() -> Unit) { Card(colors = CardDefaults.cardColors(containerColor = Panel), modifier = Modifier.fillMaxWidth()) { Column(Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(6.dp), content = content) } }
@Composable private fun Field(label: String, value: String, onValue: (String) -> Unit, secret: Boolean = false) { OutlinedTextField(value = value, onValueChange = onValue, label = { Text(label) }, modifier = Modifier.fillMaxWidth(), singleLine = true, visualTransformation = if (secret) PasswordVisualTransformation() else androidx.compose.ui.text.input.VisualTransformation.None) }
private fun number(value: Double?): String = value?.takeIf { it.isFinite() }?.let { "%.5f".format(it) } ?: "—"
private fun money(value: Double?): String = value?.takeIf { it.isFinite() }?.let { "%.2f".format(it) } ?: "—"
